#!/bin/bash

#
# This is source of Makefile.am
#

mods="
crc
dynb
listl
list
treel
tree
hash
trie
mempool
set
lru
msgq
statmath
statprint
graph
p
mtconcur
"


##############################################################################
# Headers
##############################################################################
common_headers="
ydef.h
ycommon.h
ylib.h
"

inc_headers=
for h in $common_headers; do
    inc_headers+=" $h"
done
for m in $mods; do
    inc_headers+=" y${m}.h"
done


##############################################################################
# Library
##############################################################################
common_sources="
libmain.c
"

lib_sources=
for s in $common_sources; do
    lib_sources+=" $s"
done
for m in $mods; do
    lib_sources+=" ${m}.c"
done


##############################################################################
# Program
##############################################################################
common_sources="
test_main.c
"
prog_sources=
for s in $common_sources; do
    prog_sources+=" $s"
done
for m in $mods; do
    prog_sources+=" test_${m}.c"
done


##############################################################################
# Print Makefile.am
##############################################################################
cat <<EOF
##############################################################################
#
# This is auto-generated by Makefile.sh
# DO NOT EDIT this file directly
#
##############################################################################

include_HEADERS = $inc_headers

pkglib_LTLIBRARIES = liby.la
liby_la_SOURCES = $lib_sources

bin_PROGRAMS = y
y_SOURCES = $prog_sources

y_LDADD = liby.la -lpthread -lrt -lm
EOF
