#!/bin/bash

#
# This is source of Makefile.am
#

mods="
crc
dynb
graph
hash
heap
listl
list
lru
mempool
msgq
mtpp
p
set
statmath
statprint
treel
trie
utils
"

##############################################################################
#
# Create library header (ylib.h)
#
##############################################################################
autogenfile="src/ylib.h"

cat <<EOF >$autogenfile
/*****************************************************************************
 *
 * This file is autogenerated by Makefile.sh.
 * DO NOT edit this directly
 *
 *****************************************************************************/

#ifndef __YLIb_h__
#define __YLIb_h__

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Include headers for modules
 */
#include "ydef.h"
EOF

for m in $mods; do
    echo "#include \"y${m}.h\"" >>$autogenfile
done

cat <<EOF >>$autogenfile
#ifdef __cplusplus
}
#endif

#endif /* __YLIb_h__ */

EOF

##############################################################################
#
# Create Makefile.am
#
##############################################################################
autogenfile="Makefile.am"

# Headers
# -------
common_headers="
ydef.h
ylib.h
"

inc_headers=
for h in $common_headers; do
    inc_headers+=" src/$h"
done
for m in $mods; do
    inc_headers+=" src/y${m}.h"
done


# Library
# -------
common_sources="
libmain.c
"

lib_sources=
for s in $common_sources; do
    lib_sources+=" src/$s"
done
for m in $mods; do
    lib_sources+=" src/${m}.c"
done



# Test program
# ------------
common_sources="
main.c
"
prog_sources=
for s in $common_sources; do
    prog_sources+=" tests/$s"
done
for m in $mods; do
    prog_sources+=" tests/${m}.c"
done


# Create Makefile.am
# ------------------
cat <<EOF >$autogenfile
##############################################################################
#
# This is auto-generated by Makefile.sh
# DO NOT EDIT this file directly
#
##############################################################################

include_HEADERS = $inc_headers

pkglib_LTLIBRARIES = liby.la
liby_la_SOURCES = $lib_sources

bin_PROGRAMS = y
y_SOURCES = $prog_sources
y_CFLAGS = -Isrc

y_LDADD = liby.la -lpthread -lrt -lm
EOF


##############################################################################
#
# Create Android.mk
#
##############################################################################
autogenfile="Android.mk"

cat <<EOF >$autogenfile
##############################################################################
#
# This is auto-generated by Makefile.sh
# DO NOT EDIT this file directly
#
##############################################################################

LOCAL_PATH := \$(call my-dir)

include \$(CLEAR_VARS)

LOCAL_MODULE := y

LOCAL_SRC_FILES := \\
EOF

for m in $mods; do
    echo "	${m}.c \\" >>$autogenfile
done

cat <<EOF >>$autogenfile


#LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_CFLAGS += -Wall -Werror -DCONFIG_IGNORE_CONFIG
LOCAL_C_INCLUDES +=

include \$(BUILD_SHARED_LIBRARY)
EOF
