#!/usr/bin/perl

#
# License header writer
#

use warnings;
use strict;

use constant {
    TRUE    => 1,
    FALSE   => 0,
};

my @skips = qw(config.h);

foreach my $f (<*.c *.h>) {
    my $skip = FALSE;
    foreach (@skips) {
	if ($f eq $_) {
	    $skip = TRUE;
	    last;
	}
    }
    if (FALSE == $skip) {
	wrlic($f);
    }
}


sub wrlic {
    my @d;
    my $replace = FALSE;

    open(FI, "<$_[0]") or die$!;
    foreach (<FI>) {
	push @d, $_;
    }
    close(FI);

    if (scalar @d > 0
	&& $d[0] =~ /^\/\*{78}\s*$/) {
	$replace = TRUE;
    }

    if (TRUE == $replace) {
	# remove existing license comment.
	while (scalar @d > 1) {
	    shift @d;
	    if ($d[0] =~ /^ \*{77}\/\s*$/) {
		shift @d;
		last;
	    }
	}
    }

    # Add license comments at the head of file.
    my $license =
'/******************************************************************************
 * Copyright (C) 2011, 2012, 2013, 2014
 * Younghyung Cho. <yhcting77@gmail.com>
 * All rights reserved.
 *
 * This file is part of ylib
 *
 * This program is licensed under the FreeBSD license
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation
 * are those of the authors and should not be interpreted as representing
 * official policies, either expressed or implied, of the FreeBSD Project.
 *****************************************************************************/';
    unshift @d, ($license, "\n");

    open (FO, ">$_[0]") or die$!;
    print FO @d;
    close(FO);
}
